### PR TITLE
Favico

### PR DESCRIPTION
**Pull request by sauraedron**
Other Logo svg and png. The previous one was not visible.

### CODE REVIEW

**Comment by expl0r3r** [comment]
keep up the good work, we need more voluntary work to meed our deadlines.

**Comment by expl0r3r** [comment]
@iamrajhans please make sure this gets used as our favicon

**Comment by iamrajhans** [comment]
ya sure

**Comment by sauraedron** [comment]
If i can be of any help, let me know :). Unfortunately i dont know nodejs, will try to catch up

**Pull request merged**
